kube:
  inCluster: KUBE_USE_CLUSTER
  kubeconfig: KUBE_USE_KUBECONFIG

namespaces_only: KUBE_NAMESPACES_ONLY

interval: TICK_RATE
flood_expire: FLOOD_EXPIRE
not_ready_min_time: NOT_READY_MIN_TIME

slack_url: SLACK_URL
slack_channel: SLACK_CHANNEL
slack_proxy: SLACK_PROXY

dingtalk_token: DINGTALK_TOKEN
